"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { Unit } from "@/lib/units";

interface CustomTableBuilderProps {
  units: Unit[];
}

type Orientation = "portrait" | "landscape";

interface SubCol {
  id: string;
  label: string;
}

interface Col {
  id: string;
  label: string;
  subCols: SubCol[];
}

function unitCode(building: string, apt: string): string {
  return building.replace(/\s+/g, "") + apt.replace(/\s+/g, "");
}

function uid(): string {
  return Math.random().toString(36).slice(2, 9);
}

function leafCount(col: Col): number {
  return col.subCols.length > 0 ? col.subCols.length : 1;
}

// cell key: unitCode|colId|subColId(or "")
function cellKey(unit: string, colId: string, subId: string): string {
  return `${unit}|${colId}|${subId}`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function buildTableHtml(
  cols: Col[],
  rows: string[],
  cells: Record<string, string>,
  today: string,
  orientation: Orientation
): string {
  const totalLeaf = cols.reduce((sum, c) => sum + leafCount(c), 0);
  const hasSub = cols.some((c) => c.subCols.length > 0);

  const topHeaderCells = cols
    .map((c) => `<th colspan="${leafCount(c)}" style="text-align:center;">${escapeHtml(c.label || "—")}</th>`)
    .join("");

  const subHeaderCells = hasSub
    ? cols
        .map((c) =>
          c.subCols.length > 0
            ? c.subCols.map((s) => `<th style="text-align:center;">${escapeHtml(s.label || "—")}</th>`).join("")
            : `<th></th>`
        )
        .join("")
    : "";

  const bodyRows = rows
    .map((unit, i) => {
      const bg = i % 2 === 0 ? "#ffffff" : "#f7f3ec";
      const dataCells = cols
        .map((c) => {
          if (c.subCols.length > 0) {
            return c.subCols
              .map((s) => `<td>${escapeHtml(cells[cellKey(unit, c.id, s.id)] ?? "")}</td>`)
              .join("");
          }
          return `<td>${escapeHtml(cells[cellKey(unit, c.id, "")] ?? "")}</td>`;
        })
        .join("");
      return `<tr style="background:${bg};"><td style="font-weight:600;">${escapeHtml(unit)}</td>${dataCells}</tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Emory Woods — Custom Table</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; color: #111; padding: 16px; font-size: 13px; }
  header { margin-bottom: 12px; display: flex; align-items: baseline; gap: 14px; }
  header h1 { font-size: 20px; letter-spacing: 0.08em; text-transform: uppercase; color: #1a3a25; }
  header p { color: #777; font-size: 12px; letter-spacing: 0.04em; }
  table { width: 100%; border-collapse: collapse; border: 1px solid #ddd; }
  th { background: #f5f0e8; text-align: left; padding: 6px 8px; font-size: 11px; letter-spacing: 0.06em; text-transform: uppercase; color: #555; border-bottom: 2px solid #c9a84c; border-right: 1px solid #e0d8c8; white-space: nowrap; }
  th:last-child { border-right: none; }
  td { padding: 5px 8px; border-bottom: 1px solid #eee; border-right: 1px solid #f0ebe0; font-size: 12.5px; }
  td:last-child { border-right: none; }
  tr:last-child td { border-bottom: none; }
  footer { margin-top: 10px; font-size: 11px; color: #bbb; text-align: right; letter-spacing: 0.04em; }
  @page { margin: 0.7cm; size: legal ${orientation}; }
</style>
</head>
<body>
  <header>
    <h1>Emory Woods</h1>
    <p>Custom Table &mdash; ${today}</p>
  </header>
  <table>
    <thead>
      <tr><th rowspan="${hasSub ? 2 : 1}">Unit</th>${topHeaderCells}</tr>
      ${hasSub ? `<tr>${subHeaderCells}</tr>` : ""}
    </thead>
    <tbody>${bodyRows}</tbody>
  </table>
  <footer>Generated by Emory Woods Leasing Dashboard &middot; ${rows.length} unit${rows.length === 1 ? "" : "s"} &middot; ${totalLeaf} column${totalLeaf === 1 ? "" : "s"}</footer>
</body>
</html>`;
}

const ghostButtonStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: "6px",
  background: "transparent",
  border: "1px solid var(--color-border)",
  borderRadius: "6px",
  padding: "7px 14px",
  color: "var(--color-text-muted)",
  fontFamily: "var(--font-body)",
  fontSize: "0.9rem",
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  cursor: "pointer",
  transition: "border-color 0.15s, color 0.15s",
};

const smallInputStyle: React.CSSProperties = {
  background: "var(--color-bg)",
  border: "1px solid var(--color-border)",
  borderRadius: "5px",
  padding: "5px 8px",
  color: "var(--color-text)",
  fontFamily: "var(--font-body)",
  fontSize: "0.85rem",
  outline: "none",
};

export default function CustomTableBuilder({ units }: CustomTableBuilderProps) {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState<"pick" | "build" | "preview">("pick");
  const [selectedUnits, setSelectedUnits] = useState<Set<string>>(new Set());
  const [unitSearch, setUnitSearch] = useState("");
  const [cols, setCols] = useState<Col[]>([{ id: uid(), label: "Column 1", subCols: [] }]);
  const [cells, setCells] = useState<Record<string, string>>({});
  const [orientation, setOrientation] = useState<Orientation>("landscape");
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const sortedUnits = useMemo(() => {
    function unitNum(u: Unit) { return parseInt(u.building.replace(/\D/g, ""), 10) || 0; }
    function unitStreet(u: Unit) { return u.building.replace(/\d/g, ""); }
    return [...units].sort((a, b) => {
      const s = unitStreet(a).localeCompare(unitStreet(b));
      if (s !== 0) return s;
      return unitNum(a) - unitNum(b);
    });
  }, [units]);

  const filteredUnits = useMemo(() => {
    const q = unitSearch.trim().toLowerCase();
    if (!q) return sortedUnits;
    return sortedUnits.filter((u) => {
      const code = unitCode(u.building, u.apt_number).toLowerCase();
      return code.includes(q) || u.apt_number.toLowerCase().includes(q) || (u.tenant_name ?? "").toLowerCase().includes(q);
    });
  }, [sortedUnits, unitSearch]);

  const rows = useMemo(
    () => sortedUnits.filter((u) => selectedUnits.has(unitCode(u.building, u.apt_number))).map((u) => unitCode(u.building, u.apt_number)),
    [sortedUnits, selectedUnits]
  );

  function toggleUnit(code: string) {
    setSelectedUnits((prev) => {
      const next = new Set(prev);
      if (next.has(code)) next.delete(code); else next.add(code);
      return next;
    });
  }

  function selectAllFiltered() {
    setSelectedUnits((prev) => {
      const next = new Set(prev);
      for (const u of filteredUnits) next.add(unitCode(u.building, u.apt_number));
      return next;
    });
  }

  function clearSelection() {
    setSelectedUnits(new Set());
  }

  function addColumn() {
    setCols((prev) => [...prev, { id: uid(), label: `Column ${prev.length + 1}`, subCols: [] }]);
  }

  function removeColumn(colId: string) {
    setCols((prev) => prev.filter((c) => c.id !== colId));
  }

  function renameColumn(colId: string, label: string) {
    setCols((prev) => prev.map((c) => (c.id === colId ? { ...c, label } : c)));
  }

  function addSubColumn(colId: string) {
    setCols((prev) =>
      prev.map((c) =>
        c.id === colId ? { ...c, subCols: [...c.subCols, { id: uid(), label: `Sub ${c.subCols.length + 1}` }] } : c
      )
    );
  }

  function renameSubColumn(colId: string, subId: string, label: string) {
    setCols((prev) =>
      prev.map((c) =>
        c.id === colId ? { ...c, subCols: c.subCols.map((s) => (s.id === subId ? { ...s, label } : s)) } : c
      )
    );
  }

  function removeSubColumn(colId: string, subId: string) {
    setCols((prev) =>
      prev.map((c) => (c.id === colId ? { ...c, subCols: c.subCols.filter((s) => s.id !== subId) } : c))
    );
  }

  function setCell(unit: string, colId: string, subId: string, value: string) {
    setCells((prev) => ({ ...prev, [cellKey(unit, colId, subId)]: value }));
  }

  const today = useMemo(
    () => new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }),
    []
  );

  const html = useMemo(() => buildTableHtml(cols, rows, cells, today, orientation), [cols, rows, cells, today, orientation]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
    document.addEventListener("keydown", onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [open]);

  function doPrint() {
    const win = iframeRef.current?.contentWindow;
    if (!win) return;
    win.focus();
    win.print();
  }

  function reset() {
    setStep("pick");
    setSelectedUnits(new Set());
    setUnitSearch("");
    setCols([{ id: uid(), label: "Column 1", subCols: [] }]);
    setCells({});
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        style={ghostButtonStyle}
        onMouseEnter={(e) => {
          e.currentTarget.style.borderColor = "rgba(201,168,76,0.5)";
          e.currentTarget.style.color = "var(--color-accent)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.borderColor = "var(--color-border)";
          e.currentTarget.style.color = "var(--color-text-muted)";
        }}
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
          <rect x="3" y="3" width="18" height="18" rx="2" />
          <line x1="3" y1="9" x2="21" y2="9" /><line x1="3" y1="15" x2="21" y2="15" />
          <line x1="9" y1="3" x2="9" y2="21" />
        </svg>
        Table
      </button>

      {open && (
        <div
          style={{
            position: "fixed", inset: 0, background: "rgba(0,0,0,0.65)",
            display: "flex", alignItems: "center", justifyContent: "center",
            zIndex: 110, padding: "16px",
          }}
          onClick={(e) => { if (e.target === e.currentTarget) { setOpen(false); reset(); } }}
        >
          <div
            style={{
              background: "var(--color-surface)", border: "1px solid var(--color-border)",
              borderRadius: "12px", padding: "20px", width: "100%", maxWidth: "1400px",
              maxHeight: "92dvh", display: "flex", flexDirection: "column", gap: "14px",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0 }}>
              <h2 style={{ fontFamily: "var(--font-display)", color: "var(--color-text)", fontSize: "1.2rem", fontWeight: 400, letterSpacing: "0.06em", textTransform: "uppercase", margin: 0 }}>
                Custom Table {step === "pick" ? "— Select Units" : step === "build" ? "— Build Columns" : "— Preview"}
              </h2>
              <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                {step === "pick" && (
                  <button
                    onClick={() => setStep("build")}
                    disabled={selectedUnits.size === 0}
                    style={{
                      background: selectedUnits.size === 0 ? "var(--color-border)" : "var(--color-accent)",
                      border: "none", borderRadius: "6px", padding: "8px 14px",
                      color: "#0D1A12", fontFamily: "var(--font-body)", fontSize: "0.82rem",
                      fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase",
                      cursor: selectedUnits.size === 0 ? "not-allowed" : "pointer",
                    }}
                  >
                    Next ({selectedUnits.size} selected)
                  </button>
                )}
                {step === "build" && (
                  <>
                    <button onClick={() => setStep("pick")} style={ghostButtonStyle}>Back</button>
                    <button
                      onClick={() => setStep("preview")}
                      style={{
                        background: "var(--color-accent)", border: "none", borderRadius: "6px",
                        padding: "8px 14px", color: "#0D1A12", fontFamily: "var(--font-body)",
                        fontSize: "0.82rem", fontWeight: 600, letterSpacing: "0.08em",
                        textTransform: "uppercase", cursor: "pointer",
                      }}
                    >
                      Preview
                    </button>
                  </>
                )}
                {step === "preview" && (
                  <>
                    <button onClick={() => setStep("build")} style={ghostButtonStyle}>Back</button>
                    <div style={{ display: "flex", border: "1px solid var(--color-border)", borderRadius: "6px", overflow: "hidden" }}>
                      {(["portrait", "landscape"] as Orientation[]).map((o) => (
                        <button
                          key={o}
                          onClick={() => setOrientation(o)}
                          style={{
                            padding: "7px 12px",
                            background: orientation === o ? "rgba(201,168,76,0.15)" : "transparent",
                            border: "none",
                            borderRight: o === "portrait" ? "1px solid var(--color-border)" : "none",
                            color: orientation === o ? "var(--color-accent)" : "var(--color-text-muted)",
                            fontFamily: "var(--font-body)", fontSize: "0.82rem", letterSpacing: "0.08em",
                            textTransform: "uppercase", cursor: "pointer",
                          }}
                        >
                          {o}
                        </button>
                      ))}
                    </div>
                    <button
                      onClick={doPrint}
                      style={{
                        background: "var(--color-accent)", border: "none", borderRadius: "6px",
                        padding: "8px 14px", color: "#0D1A12", fontFamily: "var(--font-body)",
                        fontSize: "0.82rem", fontWeight: 600, letterSpacing: "0.08em",
                        textTransform: "uppercase", cursor: "pointer",
                      }}
                    >
                      Print / Export
                    </button>
                  </>
                )}
                <button onClick={() => { setOpen(false); reset(); }} style={ghostButtonStyle}>Close</button>
              </div>
            </div>

            {step === "pick" && (
              <div style={{ flex: 1, minHeight: 0, display: "flex", flexDirection: "column", gap: "10px" }}>
                <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
                  <input
                    type="text"
                    placeholder="Search unit, tenant…"
                    value={unitSearch}
                    onChange={(e) => setUnitSearch(e.target.value)}
                    style={{ ...smallInputStyle, flex: 1 }}
                  />
                  <button onClick={selectAllFiltered} style={ghostButtonStyle}>Select All</button>
                  <button onClick={clearSelection} style={ghostButtonStyle}>Clear</button>
                </div>
                <div
                  style={{
                    flex: 1, minHeight: 0, overflowY: "auto",
                    display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
                    gap: "8px", border: "1px solid var(--color-border)", borderRadius: "8px", padding: "10px",
                  }}
                >
                  {filteredUnits.map((u) => {
                    const code = unitCode(u.building, u.apt_number);
                    const checked = selectedUnits.has(code);
                    return (
                      <label
                        key={code}
                        style={{
                          display: "flex", alignItems: "center", gap: "6px",
                          padding: "7px 9px", borderRadius: "6px", cursor: "pointer",
                          background: checked ? "rgba(201,168,76,0.12)" : "var(--color-bg)",
                          border: `1px solid ${checked ? "rgba(201,168,76,0.5)" : "var(--color-border)"}`,
                          fontSize: "0.85rem", color: "var(--color-text)",
                        }}
                      >
                        <input type="checkbox" checked={checked} onChange={() => toggleUnit(code)} />
                        {code}
                      </label>
                    );
                  })}
                </div>
              </div>
            )}

            {step === "build" && (
              <div style={{ flex: 1, minHeight: 0, overflowY: "auto", display: "flex", flexDirection: "column", gap: "14px" }}>
                {cols.map((col) => (
                  <div key={col.id} style={{ border: "1px solid var(--color-border)", borderRadius: "8px", padding: "12px" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" }}>
                      <input
                        type="text"
                        value={col.label}
                        onChange={(e) => renameColumn(col.id, e.target.value)}
                        style={{ ...smallInputStyle, fontWeight: 600, flex: 1, maxWidth: "260px" }}
                      />
                      <button onClick={() => addSubColumn(col.id)} style={ghostButtonStyle}>+ Sub-column</button>
                      <button
                        onClick={() => removeColumn(col.id)}
                        style={{ ...ghostButtonStyle, color: "#e05c5c", borderColor: "#e05c5c" }}
                      >
                        Remove
                      </button>
                    </div>
                    {col.subCols.length > 0 && (
                      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", paddingLeft: "12px" }}>
                        {col.subCols.map((s) => (
                          <div key={s.id} style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                            <input
                              type="text"
                              value={s.label}
                              onChange={(e) => renameSubColumn(col.id, s.id, e.target.value)}
                              style={{ ...smallInputStyle, width: "120px" }}
                            />
                            <button
                              onClick={() => removeSubColumn(col.id, s.id)}
                              style={{ ...ghostButtonStyle, padding: "5px 8px", color: "#e05c5c", borderColor: "#e05c5c" }}
                            >
                              ✕
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
                <button onClick={addColumn} style={{ ...ghostButtonStyle, alignSelf: "flex-start" }}>+ Add Column</button>

                <div style={{ marginTop: "8px", overflowX: "auto", border: "1px solid var(--color-border)", borderRadius: "8px" }}>
                  <table style={{ borderCollapse: "collapse", width: "100%", fontSize: "0.85rem" }}>
                    <thead>
                      <tr>
                        <th style={{ ...thS, position: "sticky", left: 0, background: "var(--color-surface)" }} rowSpan={cols.some((c) => c.subCols.length > 0) ? 2 : 1}>
                          Unit
                        </th>
                        {cols.map((c) => (
                          <th key={c.id} style={thS} colSpan={leafCount(c)}>{c.label || "—"}</th>
                        ))}
                      </tr>
                      {cols.some((c) => c.subCols.length > 0) && (
                        <tr>
                          {cols.map((c) =>
                            c.subCols.length > 0
                              ? c.subCols.map((s) => <th key={s.id} style={thS}>{s.label || "—"}</th>)
                              : <th key={c.id} style={thS}></th>
                          )}
                        </tr>
                      )}
                    </thead>
                    <tbody>
                      {rows.map((unit, i) => (
                        <tr key={unit}>
                          <td style={{ ...tdS, position: "sticky", left: 0, background: i % 2 === 0 ? "var(--color-bg)" : "var(--color-surface)", fontWeight: 600 }}>
                            {unit}
                          </td>
                          {cols.map((c) =>
                            c.subCols.length > 0 ? (
                              c.subCols.map((s) => (
                                <td key={s.id} style={tdS}>
                                  <input
                                    type="text"
                                    value={cells[cellKey(unit, c.id, s.id)] ?? ""}
                                    onChange={(e) => setCell(unit, c.id, s.id, e.target.value)}
                                    style={cellInputStyle}
                                  />
                                </td>
                              ))
                            ) : (
                              <td key={c.id} style={tdS}>
                                <input
                                  type="text"
                                  value={cells[cellKey(unit, c.id, "")] ?? ""}
                                  onChange={(e) => setCell(unit, c.id, "", e.target.value)}
                                  style={cellInputStyle}
                                />
                              </td>
                            )
                          )}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {step === "preview" && (
              <div style={{ flex: 1, minHeight: 0, overflow: "auto" }}>
                <iframe
                  ref={iframeRef}
                  srcDoc={html}
                  title="Custom Table Preview"
                  style={{ width: "100%", aspectRatio: orientation === "landscape" ? "14 / 8.5" : "8.5 / 14", border: "none", background: "#fff", borderRadius: "6px", display: "block" }}
                />
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}

const thS: React.CSSProperties = {
  padding: "6px 8px",
  border: "1px solid var(--color-border)",
  background: "var(--color-surface)",
  color: "var(--color-text-muted)",
  fontSize: "0.78rem",
  letterSpacing: "0.05em",
  textTransform: "uppercase",
  whiteSpace: "nowrap",
};

const tdS: React.CSSProperties = {
  padding: "3px 6px",
  border: "1px solid var(--color-border)",
  whiteSpace: "nowrap",
};

const cellInputStyle: React.CSSProperties = {
  background: "transparent",
  border: "none",
  outline: "none",
  color: "var(--color-text)",
  fontFamily: "var(--font-body)",
  fontSize: "0.85rem",
  width: "110px",
  padding: "3px 2px",
};
