"use client";

import type { Unit } from "@/lib/units";

interface ExportPDFProps {
  units: Unit[];
}

function fmt(date: string | null): string {
  if (!date) return "—";
  return new Date(date.slice(0, 10) + "T00:00:00Z").toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
}

function displayStatus(u: Unit): string {
  if (u.status === "vacant" && u.move_in_date) return "Vacant (Rented)";
  return u.status.charAt(0).toUpperCase() + u.status.slice(1);
}

export default function ExportPDF({ units }: ExportPDFProps) {
  const vacants = units.filter((u) => u.status === "vacant");
  const notices = units.filter((u) => u.status === "notice");

  function doExport() {
    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long", month: "long", day: "numeric", year: "numeric",
    });

    function buildRows(rows: Unit[], isVacant = false): string {
      const cols = isVacant ? 7 : 8;
      if (rows.length === 0) {
        return `<tr><td colspan="${cols}" style="text-align:center;color:#999;padding:16px;font-style:italic">No entries</td></tr>`;
      }
      return rows.map((u) => `
        <tr>
          <td>${u.building}</td>
          <td>${u.apt_number}</td>
          <td>${displayStatus(u)}</td>
          <td>${u.unit_type || "—"}</td>
          <td>${u.unit_condition || "—"}</td>
          <td>${u.rent || "—"}</td>
          ${isVacant
            ? `<td>${u.future_tenant || "—"}${u.future_move_in_date ? `<br><span style="color:#888;font-size:10px">Move-in: ${fmt(u.future_move_in_date)}</span>` : ""}</td>`
            : `<td>${u.move_in_date ? fmt(u.move_in_date) : u.move_out_date ? fmt(u.move_out_date) : "—"}</td>
               <td>${u.tenant_name || "—"}</td>`
          }
        </tr>
      `).join("");
    }

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Emory Woods — Leasing Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, serif; color: #111; padding: 40px; font-size: 15px; }
    header { margin-bottom: 32px; }
    header h1 { font-size: 28px; letter-spacing: 0.08em; text-transform: uppercase; color: #1a3a25; }
    header p { color: #777; font-size: 14px; margin-top: 4px; letter-spacing: 0.04em; }
    section { margin-bottom: 36px; }
    section h2 {
      font-size: 13px; letter-spacing: 0.12em; text-transform: uppercase;
      color: #888; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-bottom: 12px;
    }
    table { width: 100%; border-collapse: collapse; }
    thead tr { background: #f5f0e8; }
    th {
      text-align: left; padding: 8px 10px; font-size: 12px;
      letter-spacing: 0.1em; text-transform: uppercase; color: #555;
      border-bottom: 2px solid #c9a84c;
    }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; vertical-align: top; font-size: 14px; }
    tr:last-child td { border-bottom: none; }
    tr:nth-child(even) { background: #fafafa; }
    footer { margin-top: 40px; font-size: 12px; color: #bbb; text-align: right; letter-spacing: 0.04em; }
    @media print {
      body { padding: 24px; }
      @page { margin: 1.5cm; size: landscape; }
    }
  </style>
</head>
<body>
  <header>
    <h1>Emory Woods</h1>
    <p>Leasing Report &mdash; ${today}</p>
  </header>

  <section>
    <h2>Vacant Units (${vacants.length})</h2>
    <table>
      <thead>
        <tr>
          <th>Building</th><th>Unit</th><th>Status</th><th>Type</th>
          <th>Condition</th><th>Rent</th><th>Future Tenant</th>
        </tr>
      </thead>
      <tbody>${buildRows(vacants, true)}</tbody>
    </table>
  </section>

  <section>
    <h2>Move-Out Notices (${notices.length})</h2>
    <table>
      <thead>
        <tr>
          <th>Building</th><th>Unit</th><th>Status</th><th>Type</th>
          <th>Condition</th><th>Rent</th><th>Move-Out</th><th>Tenant</th>
        </tr>
      </thead>
      <tbody>${buildRows(notices)}</tbody>
    </table>
  </section>

  <footer>Generated by Emory Woods Leasing Dashboard</footer>

  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
  }

  return (
    <button
      onClick={doExport}
      style={{
        display: "flex",
        alignItems: "center",
        gap: "6px",
        background: "transparent",
        border: "1px solid var(--color-border)",
        borderRadius: "6px",
        padding: "7px 14px",
        color: "var(--color-text-muted)",
        fontFamily: "var(--font-body)",
        fontSize: "0.9rem",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        cursor: "pointer",
        transition: "border-color 0.15s, color 0.15s",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = "rgba(201,168,76,0.5)";
        e.currentTarget.style.color = "var(--color-accent)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = "var(--color-border)";
        e.currentTarget.style.color = "var(--color-text-muted)";
      }}
    >
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export PDF
    </button>
  );
}
